YONK-16: Added spilt module store for tests
edx-solutions/course-edx-platform-extensions pull request #5
Opened 2017-06-09 08:40 UTC by aamishbaloch

2017-09-18 14:42 UTC, aamishbaloch commented
@ziafazal Can you review this?

2017-09-20 05:52 UTC, ziafazal requested changes
@aamishbaloch could you please remove commented code.

2017-09-20 05:52 UTC, ziafazal commented on course_metadata/tests/tests.py
> +            # data=self.test_data,
commented code.

2017-09-20 17:12 UTC, aamishbaloch commented
@ziafazal removed the commented code. Can you review it?

2017-10-09 09:08 UTC, ziafazal approved these changes
👍

2017-10-09 09:13 UTC, merged