YONK-852: Course Settings added to provide support to set language
edx-solutions/course-edx-platform-extensions pull request #6
Opened 2018-01-04 10:18 UTC by aamishbaloch

Changes include the addition of Course Settings to provide support to set language of a course. Unit tests added also.

2018-01-04 10:18 UTC, aamishbaloch commented
@ziafazal Can you review this?

2018-01-04 10:49 UTC, ziafazal requested changes
@aamishbaloch completed first round of review.

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +        self.base_course_metadata_uri = '/api/server/courses_metadata/'
Can use `reverse` method to get url of the course setting view?

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +        self.assertEqual(response.status_code, 200)
Should not the response code here be 201?

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +        course_settings = CourseSetting.objects.get(id=self.course.id)
I think we should verify creation of course setting via GET call.

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +    def test_course_settings_with_no_languages(self):
We should add a unit test for updating course languages.

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +            "{}{}{}".format(self.base_course_metadata_uri, self.course.id, self.settings_uri),
can we use `self.settings_uri` here?.

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/tests/tests.py
> +        course_settings = CourseSetting.objects.get(id=self.course.id)
can we verify course setting via GET call here?

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/urls.py
> +    url(r'^{}/settings$'.format(COURSE_ID_PATTERN), views.CourseSettingView.as_view(), name='course_settings'),
can we make view name `course_settings` bit unique. may be `additional_course_settings`?

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/views.py
> +class CourseSettingView(SecureAPIView):
Permission of this view should be staff or readonly.

2018-01-04 10:49 UTC, ziafazal commented on course_metadata/views.py
> +        try:
Can we use `CourseSettingSerializer ` here?

2018-01-05 09:55 UTC, aamishbaloch commented
@ziafazal Can you review the changes?

2018-01-05 10:32 UTC, ziafazal requested changes
@aamishbaloch can you apply staff and readonly permissions and set languages to ListField in serializer?

2018-01-05 10:32 UTC, ziafazal commented on course_metadata/serializers.py
> +    def to_representation(self, instance):
can we create a field to return list of languages?

2018-01-08 08:03 UTC, aamishbaloch commented
@ziafazal Can you review the changes?

2018-01-08 09:36 UTC, ziafazal requested changes
@aamishbaloch couple of minor test case related suggestions.

2018-01-08 09:36 UTC, ziafazal commented on course_metadata/tests/tests.py
> +    def test_course_settings_get_languages(self):
This test seems redundant.

2018-01-08 09:36 UTC, ziafazal commented on course_metadata/tests/tests.py
> +    def test_course_settings_update_languages(self):
can we add a test case for non-staff user permission validation?

2018-01-08 10:37 UTC, ziafazal approved these changes
👍

2018-01-08 10:38 UTC, merged